- name: "Provision WP Database"
  mysql_db: name="{{ db }}" state=present

- name: "Grant WP user access to WP DB"
  mysql_user: name="{{ db_user }}" priv="{{ db }}.*:ALL" host="%" password={{ db_user_password }} state=present

- name: "Grant WP user access to WP DB"
  mysql_user: name="{{ db_user }}" priv="{{ db }}.*:ALL" host="localhost" password={{ db_user_password }} state=present

- name: "Set up docroot"
  file: path={{ wp_doc_root }}/{{ inventory_hostname }} state=directory owner={{ web_user }} group={{ web_group }}

- name: "Set up virtualhosts"
  template: src=etc/nginx/hhvm.conf dest=/etc/nginx/sites-available/{{ inventory_hostname }}

- name: "Enable {{ enviro }} virtualhosts"
  file: src=/etc/nginx/sites-available/{{ inventory_hostname }} dest=/etc/nginx/sites-enabled/{{ inventory_hostname }} state=link
  notify: nginx reload

- name: "Download and install WordPress for {{ enviro }}"
  command: /usr/local/bin/wp core download --path={{ wp_doc_root}}/{{ inventory_hostname }}
  sudo: yes
  sudo_user: "{{ web_user }}"

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no

- name: "Create wp-config for {{ enviro }}"
  template: src=wp/wp-config.php dest={{ wp_doc_root }}/{{ inventory_hostname }}/wp-config.php owner={{ web_user }} group={{ web_group }}

- name: "Localconfig for {{ enviro }} WordPress"
  template: src=wp/local-config.php dest={{ wp_doc_root }}/{{ inventory_hostname }}/local-config.php owner={{ web_user }} group={{ web_group }}

- name: "Object Cache for {{ enviro }} WordPress"
  template: src=wp/object-cache.php dest={{ wp_doc_root }}/{{ inventory_hostname }}/wp-content/object-cache.php owner={{ web_user }} group={{ web_group }}

- name: "Run the WP install for {{ enviro }}"
  command: /usr/local/bin/wp core install --url={{ inventory_hostname }} --title="{{ wp_site_name }}" --admin_user={{ wp_admin }} --admin_password={{ wp_admin_password }} --admin_email="admin@example.com"
  sudo: yes
  sudo_user: "{{ web_user }}"
  args:
      chdir: "{{ wp_doc_root }}/{{ inventory_hostname }}"