---
# Define root password for percona server
root_password: reallylongpassword

# Some defaults variables for percona server config file
port: 3306
bind_address: 0.0.0.0
max_allowed_packet: 16M
key_buffer: 16M
thread_stack: 192K
thread_cache_size: 8
# Uncomment following vars if you want to log queries
# sqldebug: true
# log_slow_queries: log_slow_queries    = /var/log/mysql/mysql-slow.log
# long_query_time: long_query_time      = 2
# log_queries_not_using_indexes: log-queries-not-using-indexes