---
- name: Enable HHVM repo key
  apt_key: url=http://dl.hhvm.com/conf/hhvm.gpg.key state=present

- name: Enable HHVM repo
  apt_repository: repo="deb http://dl.hhvm.com/ubuntu {{ ansible_lsb.codename }} main" state=present

- name: Install HHVM
  apt: name=hhvm state=present

- name: Do /etc/hhvm/server.ini
  template: src=etc/hhvm/server.ini dest=/etc/hhvm/server.ini owner=root group=root mode=0644
  notify: hhvm restart

- name: Do /etc/hhvm/php.ini
  template: src=etc/hhvm/php.ini dest=/etc/hhvm/php.ini owner=root group=root mode=0644
  notify: hhvm restart

- name: Ensure HHVM is running
  service: name=hhvm state=started enabled=yes
